# Generated by Django 5.1.1 on 2024-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_date_of_employment_employee_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
